# Generated by Django 3.2.19 on 2023-06-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_parking', models.BooleanField()),
                ('changing_rooms', models.BooleanField()),
                ('lockers', models.BooleanField()),
                ('sunbeds', models.BooleanField()),
                ('sauna', models.BooleanField()),
                ('pool', models.BooleanField()),
                ('personal_trainer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField(max_length=20, unique=True)),
                ('class_schedule', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='home.paymentoption')),
            ],
        ),
        migrations.CreateModel(
            name='GymLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('postcode', models.CharField(default=True, max_length=7, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('classes', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='home.gymclass')),
                ('equipment_facilities', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_facil', to='home.equipmentfacilities')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_location', to='home.gymlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.user')),
            ],
        ),
    ]
