# Generated by Django 3.2.20 on 2023-07-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_available', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'EquipmentFacilities',
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, unique=True)),
                ('class_schedule', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'GymClass',
            },
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'PaymentOption',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('user_id', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='home.paymentoption')),
            ],
            options={
                'verbose_name_plural': 'Membership',
            },
        ),
        migrations.CreateModel(
            name='GymLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('location', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('postcode', models.CharField(default=True, max_length=7, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('class_schedule', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='home.gymclass')),
                ('classes', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='home.gymclass')),
                ('equipment_facilities', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_facil', to='home.equipmentfacilities')),
            ],
            options={
                'verbose_name_plural': 'GymLocation',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_location', to='home.gymlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.user')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
    ]
