# Generated by Django 3.2.19 on 2023-06-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymlocation',
            name='name',
        ),
        migrations.AddField(
            model_name='gymlocation',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymlocation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='gymlocation',
            name='location',
            field=models.TextField(max_length=20),
        ),
    ]
