# Generated by Django 3.2.20 on 2023-08-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymlocation',
            name='equipment_facilities',
        ),
        migrations.AddField(
            model_name='gymlocation',
            name='equipment_facilities_obj1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_facil_1', to='home.equipmentfacilities'),
        ),
        migrations.AddField(
            model_name='gymlocation',
            name='equipment_facilities_obj2',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_facil_2', to='home.equipmentfacilities'),
        ),
    ]
