# Generated by Django 3.2.20 on 2023-08-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230808_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymlocation',
            name='equipment_facilities_obj1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_facilities_obj1', to='home.equipmentfacilities'),
        ),
        migrations.AlterField(
            model_name='gymlocation',
            name='equipment_facilities_obj2',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_facilities_obj2', to='home.equipmentfacilities'),
        ),
    ]
