# Generated by Django 3.2.19 on 2023-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230628_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentfacilities',
            options={'verbose_name_plural': 'EquipmentFacilities'},
        ),
        migrations.AlterModelOptions(
            name='gymclass',
            options={'verbose_name_plural': 'GymClass'},
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='day_pass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
