# Generated by Django 3.2.19 on 2023-07-01 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230628_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlocation',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
