# Generated by Django 3.2.19 on 2023-07-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gymlocation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymlocation',
            name='slug',
        ),
    ]
