# Generated by Django 3.2.19 on 2023-07-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_gymlocation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlocation',
            name='slug',
            field=models.SlugField(default=True, max_length=200, unique=True),
        ),
    ]
