# Generated by Django 3.2.19 on 2023-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gymlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymlocation',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
