# Generated by Django 3.2.19 on 2023-07-03 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gymlocation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='annual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='day_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('Full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentOption', to='home.paymentoption')),
            ],
            options={
                'verbose_name_plural': 'Membership',
            },
        ),
        migrations.CreateModel(
            name='BuyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BuyMembership', to='home.membership')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='home.paymentoption')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='Membership', to='home.membership'),
            preserve_default=False,
        ),
    ]
