# Generated by Django 3.2.19 on 2023-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gymlocation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='annual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='day_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
