# Generated by Django 3.2.20 on 2023-07-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gymlocation_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentoption',
            old_name='annual',
            new_name='Monthly',
        ),
        migrations.RemoveField(
            model_name='equipmentfacilities',
            name='changing_rooms',
        ),
        migrations.RemoveField(
            model_name='equipmentfacilities',
            name='free_parking',
        ),
        migrations.RemoveField(
            model_name='equipmentfacilities',
            name='lockers',
        ),
        migrations.RemoveField(
            model_name='equipmentfacilities',
            name='personal_trainer',
        ),
        migrations.RemoveField(
            model_name='equipmentfacilities',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='equipmentfacilities',
            name='sauna',
        ),
        migrations.RemoveField(
            model_name='equipmentfacilities',
            name='sunbeds',
        ),
        migrations.RemoveField(
            model_name='paymentoption',
            name='day_pass',
        ),
        migrations.RemoveField(
            model_name='paymentoption',
            name='monthly',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='equipmentfacilities',
            name='equipment_available',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gymlocation',
            name='class_schedule',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='home.gymclass'),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='class_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='class_schedule',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gymlocation',
            name='location',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='home.paymentoption')),
            ],
            options={
                'verbose_name_plural': 'Membership',
            },
        ),
    ]
