# Generated by Django 3.2.19 on 2023-07-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230704_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('Full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentOption', to='home.paymentoption')),
            ],
            options={
                'verbose_name_plural': 'Membership',
            },
        ),
    ]
