# Generated by Django 3.2.19 on 2023-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='gymlocation',
            name='location',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
