# Generated by Django 3.2.19 on 2023-07-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230708_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='class_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
