# Generated by Django 3.2.19 on 2023-07-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_gymlocation_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymlocation',
            old_name='schedule',
            new_name='class_schedule',
        ),
    ]
