# Generated by Django 3.2.19 on 2023-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_schedule_gymlocation_class_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='changing_rooms',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='free_parking',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='lockers',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='personal_trainer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='pool',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='sauna',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='sunbeds',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
