# Generated by Django 3.2.19 on 2023-07-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230708_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='class_schedule',
            field=models.DateTimeField(verbose_name=str),
        ),
    ]
