# Generated by Django 3.2.19 on 2023-07-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_gymclass_class_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='home.paymentoption'),
        ),
    ]
