# Generated by Django 3.2.20 on 2023-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20230708_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='changing_rooms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='free_parking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='lockers',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='personal_trainer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='pool',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='sauna',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacilities',
            name='sunbeds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
