# Generated by Django 3.2.20 on 2023-07-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20230714_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentoption',
            old_name='annual',
            new_name='Annual',
        ),
        migrations.RenameField(
            model_name='paymentoption',
            old_name='day_pass',
            new_name='Day Pass',
        ),
        migrations.RenameField(
            model_name='paymentoption',
            old_name='monthly',
            new_name='Monthly',
        ),
    ]
